[general]
fullscreen = false
early-exit = true
initial-tool = "pointer"
copy-command = "wl-copy"
output-filename = "~/Pictures/screenshots/%Y-%m-%d_%H-%M-%S.png"
save-after-copy = false
default-hide-toolbars = false
