$WALLPAPER_PATH = ~/Pictures/wallpapers/Lowpoly_Street.png
$PROFILE_PATH = ~/Pictures/profiles/spice&wolf.jpg
$SONG_PATH = ~/.config/hypr/scripts/playing.sh
$WEATHER_PATH = ~/.config/hypr/scripts/weather.sh

$CITY = Romano di Lombardia
$COUNTRY = Italy

# BACKGROUND 
background {
	path = $WALLPAPER_PATH
	blur_passes = 3
	contrast = 0.8916
	brightness = 0.8172
	vibrancy = 0.1696
	vibrancy_darkness = 0.0
}

# GENERAL
general {
	no_fade_in = false
	grace = 0
	disable_loading_bar = false
}

# INPUT FIELD
input-field {
	monitor = 
	size = 170, 45
	outline_thickness = 2
	dots_size = 0.2
	dots_spacing = 0.2
	dots_center = true
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(100, 114, 125, 0.4)
	font_color = rgba(200, 200, 200)
	fade_on_empty = false
	font_family = Geist Bold
	placeholder_text = <span foreground="##ffffff99">Enter Password</span>
	hide_input = false
	position = 0, -425
	halign = center
	valign = center
}

# Time
label {
	monitor = 
	text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
	color = rgba(216, 222, 233, 0.70)
	font_size = 85
	font_family = Geist ExtraBold
	position = 0, 310
	halign = center
	valign = center
}

# Day-Month-Date
label {
	monitor = 
	text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
	color = rgba(216, 222, 233, 0.70)
	font_size = 20
	font_family = Geist Bold
	position = 0, 400
	halign = center
	valign = center
}

# Profile-Photo
image {
	monitor = 
	path = $PROFILE_PATH
	border_color = 0xffdddddd
	border_size = 0
	size = 110
	rounding = -1
	rotate = 0
	reload_time =-1
	reload_cmd =
	position = 0, -265
	halign = center
	valign = center
}

# USER
label {
	monitor = 
	text = $USER
	color = rgba(216, 222, 233, 0.70)
	font_size = 20
	font_family = Geist Bold
	position = 0, -360
	halign = center
	valign = center
}

# CURRENT SONG
label {
	monitor = 
	text = cmd[update:1000] $SONG_PATH
	color = rgba(255, 255, 255, 0.7)
	font_size = 12
	font_family = Geist Bold
	position = 100, 0
	halign = left
	valign = center
}

# WEATHERCAST & LOCATION
label {
	monitor =
	text = cmd[update:1000] $WEATHER_PATH
	shadow_passes = 1
	shadow_boost = 0.5
	color = rgba(255, 255, 255, 0.7)
	font_size = 12
	font_family = Geist Bold
	position = 95.5, -40
	halign = left
	valign = center
}

