#!/usr/bin/env bash

CACHE="$(dirname "$0")/../.closure-cache"

sys=$(nix-store -q --requisites /run/current-system 2>/dev/null | wc -l)

hm=$(find /nix/store -maxdepth 1 -name '*-home-manager-generation' -type d 2>/dev/null \
    | tail -1 \
    | xargs -r nix-store -q --requisites \
    | wc -l)

echo "$sys system + $hm home = $((sys+hm))" > "$CACHE"
