#!/usr/bin/env bash

set -e

cd ~/nixos-dotfiles

echo "Updating flake..."
nix flake update

if git diff --quiet flake.lock; then
    echo "No flake updates available"
    exit 0
fi

echo "Rebuilding NixOS..."
sudo nixos-rebuild switch --flake .#nixos-btw

echo "Saving changes..."
git add flake.lock
git commit -m "Update flake"
git push

echo "Done!"
