hl.on("hyprland.start", function () 
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("uwsm app -- nm-applet")
    hl.exec_cmd("waybar")    
    hl.exec_cmd("swaync")
    hl.exec_cmd("awww-daemon")
    -- hl.exec_cmd("awww img ~/Pictures/wallpapers/Lowpoly_Street.png")
    hl.exec_cmd("wl-paste --type text/plain --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("avizo-service")
    hl.exec_cmd("snappy-switcher --daemon")

    hl.exec_cmd("uwsm app -- ferdium")
    hl.exec_cmd("uwsm app -- openrgb --profile \"WHITE\"")
end)
